version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ILOVECHIKEN
      POSTGRES_DB: systemreporter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  api:
    build: .
    pid: host
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:ILOVECHIKEN@db:5432/systemreporter
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
  
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./Monitoring/Grafana/provisioning/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro,Z
      - ./Monitoring/Grafana/provisioning/dashboard/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro,Z
      - ./Monitoring/Grafana/provisioning/dashboard:/var/lib/grafana/dashboards:ro,Z
    depends_on:
      - prometheus
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
    depends_on:
      - api
      - grafana
      - prometheus


volumes:
  postgres_data:
  
