apiVersion: 1

groups:
  - orgId: 1
    name: System Reporter
    folder: System Reporter
    interval: 1m
    rules:
      - uid: system-reporter-api-down
        title: System Reporter API down
        condition: B
        for: 1m
        noDataState: Alerting
        execErrState: Alerting
        annotations:
          summary: API metrics target is down
        labels:
          severity: critical
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: up{job="system-reporter"}
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: -100
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [A, 5m, now]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: -100
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: classic_conditions
